"""add_node_requests_table

Revision ID: 8a9518267406
Revises: b28fcaf0981e
Create Date: 2025-11-22 01:20:54.592970

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8a9518267406'
down_revision: Union[str, None] = 'b28fcaf0981e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('node_requests',
    sa.Column('id', sa.Integer(), nullable=False, autoincrement=True),
    sa.Column('requestor_id', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False, server_default='pending'),
    sa.Column('node_id', sa.String(), nullable=False),
    sa.Column('node_type', sa.String(), nullable=False),
    sa.Column('label', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('sector', sa.String(), nullable=True),
    sa.Column('color', sa.String(), nullable=True),
    sa.Column('metadata_json', sa.Text(), nullable=False, server_default='{}'),
    sa.Column('approver_id', sa.String(), nullable=True),
    sa.Column('approved_at', sa.DateTime(), nullable=True),
    sa.Column('rejection_reason', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_node_requests_id'), 'node_requests', ['id'], unique=False)
    op.create_index(op.f('ix_node_requests_requestor_id'), 'node_requests', ['requestor_id'], unique=False)
    op.create_index(op.f('ix_node_requests_status'), 'node_requests', ['status'], unique=False)
    op.create_index(op.f('ix_node_requests_node_id'), 'node_requests', ['node_id'], unique=False)
    op.create_index(op.f('ix_node_requests_node_type'), 'node_requests', ['node_type'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_node_requests_node_type'), table_name='node_requests')
    op.drop_index(op.f('ix_node_requests_node_id'), table_name='node_requests')
    op.drop_index(op.f('ix_node_requests_status'), table_name='node_requests')
    op.drop_index(op.f('ix_node_requests_requestor_id'), table_name='node_requests')
    op.drop_index(op.f('ix_node_requests_id'), table_name='node_requests')
    op.drop_table('node_requests')
    # ### end Alembic commands ###
